#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

case $1 in
  env | e)
    if [ ! -f "$SCRIPT_DIR/env/bin/python" ]; then
      virtualenv $SCRIPT_DIR/env
    fi
    if [ $# -ge 2 ]; then
      REQ_FILE=$2
    else
      REQ_FILE=$SCRIPT_DIR/requirements.txt
    fi
    $SCRIPT_DIR/env/bin/python -m pip install -r $REQ_FILE
    ;;
  prod | p)
    if [ $# -ge 2 ]; then
      PORT=$2
    else
      PORT=8080
    fi
    $SCRIPT_DIR/env/bin/uvicorn main:app --host 0.0.0.0 --port $PORT --log-level warning --app-dir $SCRIPT_DIR/src
    ;;
  dev | d)
    if [ $# -ge 2 ]; then
      PORT=$2
    else
      PORT=8080
    fi
    $SCRIPT_DIR/env/bin/uvicorn main:app --host 0.0.0.0 --port $PORT --app-dir $SCRIPT_DIR/src --reload
    ;;
  test | t)
    $SCRIPT_DIR/env/bin/python $SCRIPT_DIR/src/updators.py
    ;;
  *)
    echo "Usage:"
    echo "------"
    echo
    echo "e/env: Create virtual environment named env and install packages from \$2. Defaults to package spec in requirements.txt"
    echo "$ bash run e"
    echo "    env/bin/python -m pip install -r \$2"
    echo
    echo "t/test: Test updators"
    echo "$ bash run t"
    echo "    env/bin/python src/updators.py"
    echo
    echo "d/dev: Launch dev server attached to port \$2. Defaults to port 8080."
    echo "$ bash run d"
    echo "    env/bin/uvicorn main:app --host 0.0.0.0 --port \$2 --app-dir src --reload"
    echo
    echo "p/prod: Launch prod server attached to port \$2. Defaults to port 8080."
    echo "$ bash run p"
    echo "    env/bin/uvicorn main:app --host 0.0.0.0 --port \$2 --app-dir src"
    echo
    ;;
esac
